name: build-deploy
on:
  push:
    branches: [Develop]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: install
        run: npm install
      - name: build
        run: npm run build
      - name: Deploy build outputs
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_NAME }}
          key: ${{ secrets.SSH_PEM_KEY }}
          passphrase: ${{ secrets.SSH_PEM_PASSPHRASE }}
          source: "dist/*"
          strip_components: 1
          target: ${{ secrets.SERVER_PATH }}
